# ============================
# MYSQL Database Configuration
# ============================
spring.datasource.url=jdbc:mysql://localhost:3306/customercartdb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Soaib@7672

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
