server:
  port: 8081

spring:
  application:
    name: CUSTOMERMS

  datasource:
    url: jdbc:mysql://localhost:3306/customermsdb
    username: root
    password: Soaib@7672
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:   # ✅ ADDED
    prefer-ip-address: true   # ✅ ADDED